name: flutter_taxi_app_driver
description: Flutter Taxi App UI KIT for Driver

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  google_maps_flutter: ^0.5.26+4
  location: ^2.3.5
  http: 0.12.0+3
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: ^4.1.1+1
  flutter_rating_bar: ^3.0.0+1
  intro_views_flutter: ^2.5.0
  pin_code_text_field: ^1.5.1
  image_picker: ^0.6.2+3
  geolocator: ^5.3.1
  sliding_up_panel: ^1.0.2
  flutter_calendar_carousel: ^1.4.10
  material_design_icons_flutter: ^3.2.3695
  flutter_tindercard: ^0.1.8
  dio: ^3.0.9
  json_annotation: ^3.0.1
  flutter_html: ^0.11.0
  shimmer: ^1.0.1
  flutter_slidable: ^0.5.3
  cached_network_image: ^2.1.0+1
  fl_chart: ^0.9.3
  flutter_compass: ^0.3.4
  permission_handler: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.5


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/icon/
    - assets/style/
    - assets/image/directions/

  fonts:
    - family: MYRIADPRO
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.OTF
        - asset: assets/fonts/MYRIADPRO-SEMIBOLD.OTF
        - asset: assets/fonts/MYRIADPRO-BOLD.OTF
        - asset: assets/fonts/MYRIADPRO-SEMIBOLD.OTF
        - asset: assets/fonts/MYRIADPRO-COND.OTF
        - asset: assets/fonts/MYRIADPRO-CONDIT.OTF
        - asset: assets/fonts/MyriadPro-Light.otf
